### ISSUE TITLE
Digital persona SDK for Linux

### ISSUE THREAD

**Issue by nwashangai** [iamonuwa/Digital-Persona-SDK#2]
Can anyone please provide the SDK for Linux?? 
I really need it for my work on Linux Ubuntu distro

**Comment by nomoney4me** [comment]
I haven't tested this library yet but I've heard someone used this for the uareu 4500.
Might want to consider playing with this: https://www.freedesktop.org/wiki/Software/fprint/libfprint

**Comment by nwashangai** [comment]
@nomoney4me thanks i really appreciate this, am going through it and hopefully it will serve me

**Comment by iamonuwa** [comment]
@nwashangai, this is a windows sdk

**Comment by nwashangai** [comment]
@iamonuwa, can I get the Linux sdk??

**Comment by iamonuwa** [comment]
@nwashangai no you can't
