### ISSUE TITLE
Is there any version for Linux(Android)

### ISSUE THREAD

**Issue by joshuachinemezu** [iamonuwa/Digital-Persona-SDK#3]
Hello nice of you for making this open source, please is there any Linux(Android) version of this SDK.
Thanks for a receptive response

**Comment by iamonuwa** [comment]
You'll need to rely on the android fingerprint.

**Comment by joshuachinemezu** [comment]
Thanks for the quick response, but I am yet to find a tutorial on how to connect the android fingerprint to a web server. Any suggestions on how to go about this?

**Comment by iamonuwa** [comment]
At the moment, no. Try developer.android.com

**Comment by joshuachinemezu** [comment]
Ok thanks man
